//Add event listener for each element in nodeArray
function addEvents(nodeArray, callback, event) {
  for (var i = 0; i < nodeArray.length; i++) {
    nodeArray[i].addEventListener(event, callback, false);
  }
}


//getToken generated by Rails(usually placed in meta holder
function getToken() {
  var metaTags = document.getElementsByTagName("meta"),
    token = "";
  for (var i = 0; i < metaTags.length; i++) {
    if (metaTags[i].name == "csrf-token") {
      token = metaTags[i].getAttribute("content");
      break;
    }
  }
  return token;
}

//Ajax request template
function sendAjax(mac, action) {
  var token = getToken(),
    modalWindow = document.querySelector('.modal-window'),
    url = '',
    req = JSON.stringify({
      authenticity_token: getToken(),
      mac: mac
    }),
    xhr = new XMLHttpRequest();

  switch (action) {
    case 'delete':
      url = "/profile/delete_device";
      break;
    case 'rename':
      var new_label = document.getElementById('new_label').value;
      url = "/profile/rename_device";
      req = JSON.stringify({
        authenticity_token: getToken(),
        mac: mac,
        new_label: new_label
      });
      break;
    case 'unsubscribe':
      url = "/profile/unsubscribe";
      break;
  }

  xhr.open('POST', url, true);
  xhr.setRequestHeader('Content-type', 'application/json; charset=utf-8');

  xhr.onreadystatechange = function() {
    if (xhr.readyState != 4) return;

    if (xhr.status != 200) {
      alert(xhr.status + ': ' + xhr.statusText);
    } else {
      setStatus(modalWindow, JSON.parse(xhr.responseText).result);
      if (window.needReload) {
        setTimeout(function() {
          location.reload();
        }, 1500)
      }
    }
  };
  xhr.send(req);

  modalWindow.innerHTML = "<div class='spinner'></div>";
  //button.disabled = true;
}

function createModalWindow(mac, action) {
  var modalWindow = document.createElement('div');
  modalWindow.classList.add('modal-overlay');

  switch (action) {
    case 'delete':
      var headerMessage = "Вы действительно хотите удалить это устройство ?",
        textMessage = "Данное устройство будет отвязано от вашей учетной записи",
        btnMessage = "Да, удалить";
      break;
    case 'rename':
      var headerMessage = "Введите новое имя для вашего устройства",
        textMessage = "<input type='text' id='new_label'>",
        btnMessage = "Сменить";
      window.needReload = true;
      break;
    case 'unsubscribe':
      var headerMessage = "Вы действительно удалить подписку для этого устройства ?",
        textMessage = "Автоматическое снятие денег с вашей карты будет отменено",
        btnMessage = "Да, удалить";
      break;
  }
  modalWindow.innerHTML = "<div class='modal-window'><h2 class='modal-header'>" + headerMessage + "</h2><p class='modal-message'>" + textMessage + "</p><div class='button-wrapper'><button class='button' onclick=sendAjax('" + mac + "','" + action + "')>" + btnMessage + "</button> <button class='button' onclick='removeModalWindow()'>Отмена</button></div></div>"
  document.body.appendChild(modalWindow);
}

//Function for creating popup modal window
function createModalWindow(mac, action) {
  var modalWindow = document.createElement('div');
  modalWindow.classList.add('modal-overlay');

  switch (action) {
    case 'delete':
      var headerMessage = "Вы действительно хотите удалить это устройство ?",
        textMessage = "Данное устройство будет отвязано от вашей учетной записи",
        btnMessage = "Да, удалить";
      break;
    case 'rename':
      var headerMessage = "Введите новое имя для вашего устройства",
        textMessage = "<input type='text' id='new_label'>",
        btnMessage = "Сменить";
      window.needReload = true;
      break;
    case 'unsubscribe':
      var headerMessage = "Вы действительно удалить подписку для этого устройства ?",
        textMessage = "Автоматическое снятие денег с вашей карты будет отменено",
        btnMessage = "Да, удалить";
      break;
  }
  modalWindow.innerHTML = "<div class='modal-window'><h2 class='modal-header'>" + headerMessage + "</h2><p class='modal-message'>" + textMessage + "</p><div class='button-wrapper'><button class='button' onclick=sendAjax('" + mac + "','" + action + "')>" + btnMessage + "</button> <button class='button' onclick='removeModalWindow()'>Отмена</button></div></div>"
  document.body.appendChild(modalWindow);
}

//function for removing that modal window
function removeModalWindow() {
  var modalWindow = document.querySelector('.modal-overlay');
  modalWindow.remove();
}

//Current Time for timestamps and rnd
function getCurrentTime() {
  var now = new Date();
  return now.getTime();
}
